development:
  adapter: postgresql
  encoding: unicode
  database: cfb_dev

test:
  adapter: postgresql
  encoding: unicode
  database: cfb_test

production:
  adapter: postgresql
  encoding: unicode
  database: cfb_prod
